services:
  website:
    build:
      context: ./website
    entrypoint: ./entrypoint.sh
    container_name: saffron-website
    expose:
      - "8000"
    depends_on:
      - db 
    environment:
      - DEBUG=True
      - DB_NAME=SaffronDB
      - DB_USER=SaffronUser
      - DB_PASSWORD=qWff$4i332
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./website:/app

  db:
    image: postgres:13
    container_name: saffron-database
    environment:
      POSTGRES_DB: SaffronDB
      POSTGRES_USER: SaffronUser
      POSTGRES_PASSWORD: qWff$4i332
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./website/static:/usr/share/nginx/html/static
      - ./website/media:/usr/share/nginx/html/media
    depends_on:
      - website
    container_name: saffron-nginx

volumes:
  postgres_data:
