# Generated by Django 5.0.6 on 2024-06-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
