# Generated by Django 5.0.6 on 2024-06-30 17:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('send_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('content', tinymce.models.HTMLField()),
                ('price', models.PositiveIntegerField(default=0, help_text='based on kg')),
                ('image', models.ImageField(upload_to='product')),
                ('views', models.PositiveIntegerField(default=0)),
                ('off_percentage', models.PositiveIntegerField(default=0)),
                ('owner', models.CharField(max_length=150)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rate', models.PositiveIntegerField(default=3)),
            ],
        ),
    ]
